version: '2'
services:
  postgres:
    image: postgres
  web:
    build: .
    ports:
      - "8080:8080"
    # Not explicitly naming links is a bad idea since compose gives them other
    # names, so when you lookup by hostname it can't find it with ENOTFOUND.
    links:
      - postgres
    depends_on:
      - postgres
